[workspace]
resolver = "2"
members = [
    "node",
    "pallets/template",
    # "pallets/user",
    # "pallets/store-words",
    "pallets/cloud-api",
    # "pallets/create-buckets",
    "runtime",
]
[profile.release]
panic = "unwind"
