[workspace]
resolver = "2"
members = [
    "node",
    "pallets/template",
    "pallets/ocw",
    "pallets/user",
    "pallets/store-words",
    "cloud", 
    "pallets/cloud_mod",
    "pallets/cloud-bucket",
]
[profile.release]
panic = "unwind"
