[package]
name = "cloud_mod"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "cloud_mod_lib"

[dependencies]
reqwest = { version = "0.11.22", features = ["json"] }
serde_json = "1.0.108"

